org: n8finch
app: breaking-news-app
service: bref-breaking-news-service-event
frameworkVersion: "3"

custom:
  tableName: "breaking-news-table-${sls:stage}"

provider:
  name: aws
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [BreakingNewsTable, Arn]
  environment:
    DYNAMODB_TABLE: ${self:custom.tableName}
  httpApi:
    cors: true

plugins:
  - ./vendor/bref/bref

functions:
  get:
    handler: get.php
    description: "Get the breaking news item by ID."
    runtime: php-82
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    events:
      - httpApi: "GET /breaking-news/{id}"
  create:
    handler: create.php
    description: "Create a breaking news item."
    runtime: php-82
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    events:
      - httpApi: "POST /breaking-news"

resources:
  Resources:
    BreakingNewsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

# Exclude files from deployment
package:
  patterns:
    - "!tests/**"
